version: '3'

services:
  
  samba:
    build: .
    container_name: samba
    tty: true
    stdin_open: true
    ports:
      - "11111:139"
      - "11112:445"
    
    volumes:
      - ./usr1:/usr1
      - ./usr2:/usr2
      - ./public:/public
      - ./private:/private
      - ./cfg:/etc/samba