version: '3'

services:
  
  samba:
    build: .
    container_name: samba
    tty: true
    stdin_open: true
    ports:
      - "139:139"
      - "445:445"
    
    volumes:
      - ./usr1:/mnt/usr1
      - ./usr2:/mnt/usr2
      - ./public:/mnt/public
      - ./private:/mnt/private
      - ./cfg:/etc/