version: '3'

services:
  
  samba:
    build: .
    container_name: samba
    tty: true
    stdin_open: true
    ports:
      - "139:139"
      - "445:445"
    
    volumes:
      - ./usr1:/home/samba/share/usr1
      - ./usr2:/home/samba/share/usr2
      - ./public:/home/samba/share/public
      - ./private:/home/samba/share/private
      - ./cfg/samba/smb.conf:/etc/samba/smb.conf